databases:
  - name: kunda
    databaseName: kunda_db
    user: kunda

services:
  - type: web
    name: kunda
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn kunda.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kunda
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4